WebBanQuanAo/Models/banner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string meta { get; set; }
        public string img { get; set; }
    }
}

WebBanQuanAo/Areas/Admin/Controllers/bannersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanQuanAo.Models;

namespace WebBanQuanAo.Areas.Admin.Controllers
{
    public class bannersController : Controller
    {
        private ShopQuanAoOnlineEntities6 db = new ShopQuanAoOnlineEntities6();

        // GET: Admin/banners
        public ActionResult Index()
        {
            return View(db.banners.ToList());
        }

        // GET: Admin/banners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // GET: Admin/banners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/banners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name,meta,img")] banner banner)
        {
            if (ModelState.IsValid)
            {
                db.banners.Add(banner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(banner);
        }

        // GET: Admin/banners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Admin/banners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name,meta,img")] banner banner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(banner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(banner);
        }

        // GET: Admin/banners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Admin/banners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            banner banner = db.banners.Find(id);
            db.banners.Remove(banner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanQuanAo/Areas/Admin/Views/banners/Create.cshtml
@model WebBanQuanAo.Models.banner

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MyLayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>banner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBanQuanAo/Areas/Admin/Views/banners/Delete.cshtml
@model WebBanQuanAo.Models.banner

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MyLayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>banner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebBanQuanAo/Areas/Admin/Views/banners/Details.cshtml
@model WebBanQuanAo.Models.banner

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_MyLayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>banner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBanQuanAo/Areas/Admin/Views/banners/Edit.cshtml
@model WebBanQuanAo.Models.banner

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MyLayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>banner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBanQuanAo/Areas/Admin/Views/banners/Index.cshtml
@model IEnumerable<WebBanQuanAo.Models.banner>
@using WebBanQuanAo.Help
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MyLayoutAdmin.cshtml";
}
<style>
    th, td {
        text-align: center;
    }

        td p {
            height: 50px;
            overflow-y: hidden;
            text-overflow: ellipsis;
        }
</style>
@section _Header
{
    <!-- DataTables CSS -->
    <link href="~/Areas/Admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Areas/Admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
}
<div class="btn-group">
    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span> Thêm mới", "Create", "Create", "banners", routeValues: new { }, htmlAttributes: new { @class = "btn btn-primary" })
</div>
<div class="row">
<div class="col-lg-12">
    <div class="panel panel-red">
        <div class="panel-heading">
            Dữ Liệu Trên Bảng Ghi
        </div>
        <div class="panel-body">
            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>
                            Tên
                        </th>
                        <th>
                            Loại
                        </th>
                        <th>
                            Hình
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.meta)
                </td>
                <td>
                    <img src="~/Content/images/@item.img" width="50px" />
                </td>
                <td>
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Chỉnh Sửa", "Edit", "banners", new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-zoom-in'></span>", "Chi Tiết", "Details", "banners", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-primary" })
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Xóa", "Delete", "banners", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-danger" })


                </td>

            </tr>
}


                </tbody>
            </table>
            <!-- /.table-responsive -->

        </div>

        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->
    </div>


    @section _Footer
{
        <!-- DataTables JavaScript -->
        <script src="~/Areas/Admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
        <script src="~/Areas/Admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
        <script src="~/Areas/Admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
        <!-- Page-Level Demo Scripts - Tables - Use for reference -->
        <script>
            $(document).ready(function () {
                $('#dataTables-example').DataTable({
                    responsive: true

                });
            });
        </script>
    }